version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /flask-app/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /flask-app/docker-credentials/password
    DOCKER_REGISTRY_URL: /flask-app/docker-credentials/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/flask-app-aws-cicd:latest" .
      - docker push "docker.io/hemanthgangula/flask-app-aws-cicd:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
